use_frameworks!

target 'PH4BibleManager_Example' do
  pod 'PH4BibleManager', :path => '../'

  target 'PH4BibleManager_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
